// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv-VXfckOfFjx5nxsgiZt2uUr-2SeTm4U',
    appId: '1:45365554782:web:241c37c2e58fe9a9db4ecf',
    messagingSenderId: '45365554782',
    projectId: 'expense-tracker-de839',
    authDomain: 'expense-tracker-de839.firebaseapp.com',
    storageBucket: 'expense-tracker-de839.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9mNosE5STMeujJcxRr9LkvsWp79afrHk',
    appId: '1:45365554782:android:1f0ea0d9c11e43d8db4ecf',
    messagingSenderId: '45365554782',
    projectId: 'expense-tracker-de839',
    storageBucket: 'expense-tracker-de839.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIMyO5iltYDYPN6jqs47vuZIIfsuRkg2U',
    appId: '1:45365554782:ios:1ebc23dbc5974fd9db4ecf',
    messagingSenderId: '45365554782',
    projectId: 'expense-tracker-de839',
    storageBucket: 'expense-tracker-de839.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv-VXfckOfFjx5nxsgiZt2uUr-2SeTm4U',
    appId: '1:45365554782:web:fc84747a56f9117adb4ecf',
    messagingSenderId: '45365554782',
    projectId: 'expense-tracker-de839',
    authDomain: 'expense-tracker-de839.firebaseapp.com',
    storageBucket: 'expense-tracker-de839.firebasestorage.app',
  );
}
