// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        ); 
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHU6snzzehtoNrqf6DxDMD-MuKfCpadf0',
    appId: '1:150563261963:web:32461119d84191d109010e',
    messagingSenderId: '150563261963',
    projectId: 'fir-project-2d238',
    authDomain: 'fir-project-2d238.firebaseapp.com',
    storageBucket: 'fir-project-2d238.firebasestorage.app',
    measurementId: 'G-YPJ0HWXR6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBer6wUMuY4tX-_TVaOE1bHYOqSURgheJA',
    appId: '1:150563261963:android:a212e6871a1e5bc709010e',
    messagingSenderId: '150563261963',
    projectId: 'fir-project-2d238',
    storageBucket: 'fir-project-2d238.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ4C20NjlqsQvn2q7vtz8XDrV3xbIit58',
    appId: '1:150563261963:ios:4990ea60ae491d9009010e',
    messagingSenderId: '150563261963',
    projectId: 'fir-project-2d238',
    storageBucket: 'fir-project-2d238.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ4C20NjlqsQvn2q7vtz8XDrV3xbIit58',
    appId: '1:150563261963:ios:4990ea60ae491d9009010e',
    messagingSenderId: '150563261963',
    projectId: 'fir-project-2d238',
    storageBucket: 'fir-project-2d238.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHU6snzzehtoNrqf6DxDMD-MuKfCpadf0',
    appId: '1:150563261963:web:13a6af2e82b8ffda09010e',
    messagingSenderId: '150563261963',
    projectId: 'fir-project-2d238',
    authDomain: 'fir-project-2d238.firebaseapp.com',
    storageBucket: 'fir-project-2d238.firebasestorage.app',
    measurementId: 'G-TF6WGE44NF',
  );
}
